---
# galaxy-nginx.yml
- hosts: web
  become: true
  roles:
    - role: geerlingguy.nginx
      vars:
        nginx_remove_default_vhost: true
        nginx_vhosts:
          - listen: "80 default_server"
            server_name: "_"
            root: "/var/www/html"
            index: "index.html"
            state: present

  tasks:
    - name: Create a simple homepage
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
          <!doctype html>
          <html>
          <head><title>Ansible Nginx Test</title></head>
          <body style="font-family:sans-serif;text-align:center;">
            <h1>It works! ✅</h1>
            <p>Deployed via Ansible + geerlingguy.nginx role.</p>
          </body>
          </html>
        mode: "0644"
